image: docker:latest

services:
  - docker:dind

variables:
  CONTAINER_RELEASE_IMAGE: build.datapunt.amsterdam.nl:5000/fixxx/rembrandtplein-web:latest
  DOCKER_DRIVER: overlay

build-master:
  stage: build
  script:
    - docker build -t "$CONTAINER_RELEASE_IMAGE" .
    - docker push "$CONTAINER_RELEASE_IMAGE"
  only:
    - master

build:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master